const CONFIG = {
    titleWeb: 'Boringg',
    introTitle: 'Bấm tiếp tục đii ',
    introDesc: 'Bấm đi mà',
    btnIntro: 'Continue',
    title: 'Đi ăn gà honggg 🥰',
    desc: 'Ăn gàaaa',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Mày sẽ bao tao chứ <33',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Chắc chắn rồii :>>',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối nay 7h, mình qua đón đi chơi nha.',
    btnAccept: 'Okiiiii lun <3',
}
